[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://app.kontent.ai"
    Content-Security-Policy = "frame-ancestors https://app.kontent.ai https://*.kontent.ai"
